<?php

/**
 * Implements hook_theme().
 */
function symfony_mailer_theme($existing, $type, $theme, $path) {
  return [
    'email' => [
      'variables' => [
        'content' => '',
        'message' => NULL,
        'is_html' => TRUE,
      ],
      'mail theme' => TRUE,
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK() for email.
 */
function symfony_mailer_theme_suggestions_email(array $variables) {
  $key_array = explode('.', $variables['message']->getKey());
  $key = 'email__';
  while ($key_array) {
    $key .= '__' . array_shift($key_array);
    $suggestions[] = $key;
  }

  return $suggestions;
}

/**
 * Prepares variables for email template.
 *
 * Default template: email.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - message: An associative array containing the Email object.
 *   - is_html: True if generating HTML output, false for plain text.
 */
function template_preprocess_email(&$variables) {
}
