<?php

/**
 * Implements hook_theme().
 */
function symfony_mailer_theme($existing, $type, $theme, $path) {
  return [
    'email' => [
      'variables' => [
        'email' => NULL,
        'is_html' => TRUE,
      ],
      'mail theme' => TRUE,
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK() for email.
 */
function symfony_mailer_theme_suggestions_email(array $variables) {
  return array_slice($variables['email']->getKeySuggestions('email__', '__'), 1);
}

/**
 * Prepares variables for email template.
 *
 * Default template: email.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - message: An associative array containing the Email object.
 *   - is_html: True if generating HTML output, false for plain text.
 */
function template_preprocess_email(&$variables) {
  $variables['content'] = $variables['email']->getContent();
  $variables['params'] = $variables['email']->getParams();
}
